[package]
name = "prism"
version = "0.1.0"
description = "A local Blender model rendering workspace"
authors = ["Twisted Signal"]
edition = "2021"

[lib]
name = "prism_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
uuid = { version = "1", features = ["v4"] }
