[package]
name = "twistedsignal/prism"
description = "Render Roblox Studio models into icons with Blender"
version = "0.11.0"
license = "MIT"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

[dependencies]
vide = "centau/vide@0.4.0"
