"""Frozen P1 wire settings. Never reorder or modify; introduce a new version instead."""

FIELDS = ({'key': 'pitch', 'type': 'number', 'default': 0, 'min': -180, 'max': 180, 'step': 1},
 {'key': 'yaw', 'type': 'number', 'default': 0, 'min': -180, 'max': 180, 'step': 1},
 {'key': 'roll', 'type': 'number', 'default': 0, 'min': -180, 'max': 180, 'step': 1},
 {'key': 'cameraRotation', 'type': 'number', 'default': 39.5, 'min': -180, 'max': 180, 'step': 0.5},
 {'key': 'cameraElevation', 'type': 'number', 'default': 27.5, 'min': -89, 'max': 89, 'step': 0.5},
 {'key': 'cameraRoll', 'type': 'number', 'default': 0, 'min': -180, 'max': 180, 'step': 0.5},
 {'key': 'zoom', 'type': 'number', 'default': 1, 'min': 0.1, 'max': 5, 'step': 0.01},
 {'key': 'orthographic', 'type': 'bool', 'default': True},
 {'key': 'fov', 'type': 'number', 'default': 30, 'min': 5, 'max': 120, 'step': 0.5},
 {'key': 'fovAuto', 'type': 'bool', 'default': True},
 {'key': 'exposure', 'type': 'number', 'default': 0, 'min': -3, 'max': 3, 'step': 0.01},
 {'key': 'sunColor', 'type': 'color', 'default': '#FFFFFF'},
 {'key': 'sunIntensity', 'type': 'number', 'default': 1, 'min': 0, 'max': 3, 'step': 0.01},
 {'key': 'sunRotation', 'type': 'number', 'default': -29.5, 'min': -180, 'max': 180, 'step': 0.5},
 {'key': 'sunElevation', 'type': 'number', 'default': 31, 'min': -89, 'max': 89, 'step': 0.5},
 {'key': 'castShadows', 'type': 'bool', 'default': True},
 {'key': 'shadowIntensity', 'type': 'number', 'default': 0.32, 'min': 0, 'max': 1, 'step': 0.01},
 {'key': 'secondaryColor', 'type': 'color', 'default': '#FFFFFF'},
 {'key': 'secondaryIntensity', 'type': 'number', 'default': 1, 'min': 0, 'max': 3, 'step': 0.01},
 {'key': 'ambientColor', 'type': 'color', 'default': '#FFFFFF'},
 {'key': 'ambientIntensity', 'type': 'number', 'default': 0.5145, 'min': 0, 'max': 2, 'step': 0.01},
 {'key': 'transparency', 'type': 'bool', 'default': True},
 {'key': 'specular', 'type': 'number', 'default': 0, 'min': 0, 'max': 1, 'step': 0.01},
 {'key': 'roughness', 'type': 'number', 'default': 0.5, 'min': 0, 'max': 1, 'step': 0.01},
 {'key': 'saturation', 'type': 'number', 'default': 1, 'min': 0, 'max': 3, 'step': 0.01},
 {'key': 'contrast', 'type': 'number', 'default': 1, 'min': 0, 'max': 3, 'step': 0.01},
 {'key': 'brightness', 'type': 'number', 'default': 1, 'min': 0, 'max': 3, 'step': 0.01},
 {'key': 'outlineSize', 'type': 'number', 'default': 10, 'min': 0, 'max': 40, 'step': 1},
 {'key': 'outlineColor', 'type': 'color', 'default': '#000000'},
 {'key': 'dropShadow', 'type': 'bool', 'default': True},
 {'key': 'shadowColor', 'type': 'color', 'default': '#000000'},
 {'key': 'shadowOpacity', 'type': 'number', 'default': 0.35, 'min': 0, 'max': 1, 'step': 0.01},
 {'key': 'shadowBlur', 'type': 'number', 'default': 25, 'min': 0, 'max': 60, 'step': 0.5},
 {'key': 'shadowOffsetX', 'type': 'number', 'default': 12, 'min': -64, 'max': 64, 'step': 1},
 {'key': 'shadowOffsetY', 'type': 'number', 'default': 12, 'min': -64, 'max': 64, 'step': 1},
 {'key': 'glow', 'type': 'bool', 'default': False},
 {'key': 'glowColor', 'type': 'color', 'default': '#FFD966'},
 {'key': 'glowOpacity', 'type': 'number', 'default': 0.8, 'min': 0, 'max': 1, 'step': 0.01},
 {'key': 'glowSize', 'type': 'number', 'default': 16, 'min': 0, 'max': 64, 'step': 1},
 {'key': 'innerShadow', 'type': 'bool', 'default': False},
 {'key': 'innerShadowColor', 'type': 'color', 'default': '#000000'},
 {'key': 'innerShadowOpacity', 'type': 'number', 'default': 0.5, 'min': 0, 'max': 1, 'step': 0.01},
 {'key': 'innerShadowBlur', 'type': 'number', 'default': 6, 'min': 0, 'max': 40, 'step': 0.5},
 {'key': 'innerShadowOffsetX', 'type': 'number', 'default': 4, 'min': -32, 'max': 32, 'step': 1},
 {'key': 'innerShadowOffsetY', 'type': 'number', 'default': 4, 'min': -32, 'max': 32, 'step': 1},
 {'key': 'colorOverlay', 'type': 'bool', 'default': False},
 {'key': 'colorOverlayColor', 'type': 'rgba', 'default': '#FF3B3B80'},
 {'key': 'celShading', 'type': 'bool', 'default': False},
 {'key': 'celLevels', 'type': 'number', 'default': 3, 'min': 2, 'max': 8, 'step': 1},
 {'key': 'heatmap', 'type': 'bool', 'default': False},
 {'key': 'heatmapSource', 'type': 'select', 'default': 'brightness', 'options': ['brightness', 'depth']},
 {'key': 'duotone', 'type': 'bool', 'default': False},
 {'key': 'duotoneShadow', 'type': 'color', 'default': '#1B1464'},
 {'key': 'duotoneHighlight', 'type': 'color', 'default': '#FFC857'},
 {'key': 'tritone', 'type': 'bool', 'default': False},
 {'key': 'tritoneShadow', 'type': 'color', 'default': '#14213D'},
 {'key': 'tritoneMidtone', 'type': 'color', 'default': '#E5383B'},
 {'key': 'tritoneHighlight', 'type': 'color', 'default': '#FCECC9'},
 {'key': 'halftone', 'type': 'bool', 'default': False},
 {'key': 'halftoneSize', 'type': 'number', 'default': 6, 'min': 2, 'max': 32, 'step': 1},
 {'key': 'halftoneStrength', 'type': 'number', 'default': 0.6, 'min': 0, 'max': 1, 'step': 0.01},
 {'key': 'dither', 'type': 'bool', 'default': False},
 {'key': 'ditherLevels', 'type': 'number', 'default': 4, 'min': 2, 'max': 16, 'step': 1},
 {'key': 'ditherScale', 'type': 'number', 'default': 1, 'min': 1, 'max': 8, 'step': 1},
 {'key': 'pixelate', 'type': 'bool', 'default': False},
 {'key': 'pixelSize', 'type': 'number', 'default': 8, 'min': 2, 'max': 64, 'step': 1},
 {'key': 'chromaticAberration', 'type': 'bool', 'default': False},
 {'key': 'chromaticAmount', 'type': 'number', 'default': 4, 'min': 1, 'max': 32, 'step': 1},
 {'key': 'crt', 'type': 'bool', 'default': False},
 {'key': 'crtScanlines', 'type': 'number', 'default': 0.5, 'min': 0, 'max': 1, 'step': 0.01},
 {'key': 'crtCurvature', 'type': 'number', 'default': 0.2, 'min': 0, 'max': 1, 'step': 0.01},
 {'key': 'bloom', 'type': 'bool', 'default': False},
 {'key': 'bloomThreshold', 'type': 'number', 'default': 0.7, 'min': 0, 'max': 1, 'step': 0.01},
 {'key': 'bloomIntensity', 'type': 'number', 'default': 1, 'min': 0, 'max': 3, 'step': 0.01},
 {'key': 'bloomRadius', 'type': 'number', 'default': 12, 'min': 1, 'max': 64, 'step': 1},
 {'key': 'xray', 'type': 'bool', 'default': False},
 {'key': 'xrayColor', 'type': 'color', 'default': '#7FD4FF'},
 {'key': 'xrayFalloff', 'type': 'number', 'default': 1.5, 'min': 0.5, 'max': 4, 'step': 0.05},
 {'key': 'depthTint', 'type': 'bool', 'default': False},
 {'key': 'depthTintColor', 'type': 'color', 'default': '#6FA8FF'},
 {'key': 'depthTintStrength', 'type': 'number', 'default': 0.5, 'min': 0, 'max': 1, 'step': 0.01},
 {'key': 'depthOutlineSize', 'type': 'number', 'default': 0, 'min': 0, 'max': 12, 'step': 0.5},
 {'key': 'depthOutlineColor', 'type': 'color', 'default': '#000000'},
 {'key': 'vignette', 'type': 'bool', 'default': False},
 {'key': 'vignetteColor', 'type': 'color', 'default': '#000000'},
 {'key': 'vignetteStrength', 'type': 'number', 'default': 0.5, 'min': 0, 'max': 1, 'step': 0.01},
 {'key': 'vignetteOpacity', 'type': 'number', 'default': 0.6, 'min': 0, 'max': 1, 'step': 0.01},
 {'key': 'text', 'type': 'text', 'default': '', 'maxLength': 120},
 {'key': 'textEmojiProvider',
  'type': 'select',
  'default': 'google',
  'options': ['apple', 'google', 'facebook', 'twitter']},
 {'key': 'textFont', 'type': 'text', 'default': '', 'maxLength': 100},
 {'key': 'textSize', 'type': 'number', 'default': 64, 'min': 8, 'max': 256, 'step': 1},
 {'key': 'textWeight', 'type': 'number', 'default': 400, 'min': 100, 'max': 900, 'step': 100},
 {'key': 'textBold', 'type': 'bool', 'default': False},
 {'key': 'textItalic', 'type': 'bool', 'default': False},
 {'key': 'textOffsetX', 'type': 'number', 'default': 0, 'min': -512, 'max': 512, 'step': 1},
 {'key': 'textOffsetY', 'type': 'number', 'default': 0, 'min': -512, 'max': 512, 'step': 1},
 {'key': 'textRotation', 'type': 'number', 'default': 0, 'min': -180, 'max': 180, 'step': 1},
 {'key': 'textLetterSpacing', 'type': 'number', 'default': 1, 'min': 0.5, 'max': 3, 'step': 0.05},
 {'key': 'textLineSpacing', 'type': 'number', 'default': 1, 'min': 0.5, 'max': 3, 'step': 0.05},
 {'key': 'textColor', 'type': 'rgba', 'default': '#FFFFFFFF'},
 {'key': 'textGradient', 'type': 'bool', 'default': False},
 {'key': 'textGradientColor', 'type': 'rgba', 'default': '#FF8A00FF'},
 {'key': 'textGradientAngle', 'type': 'number', 'default': 90, 'min': -180, 'max': 180, 'step': 1},
 {'key': 'textUnderline', 'type': 'bool', 'default': False},
 {'key': 'textStrikethrough', 'type': 'bool', 'default': False},
 {'key': 'textOutlineSize', 'type': 'number', 'default': 0, 'min': 0, 'max': 24, 'step': 0.5},
 {'key': 'textOutlineColor', 'type': 'rgba', 'default': '#000000FF'},
 {'key': 'textGlow', 'type': 'bool', 'default': False},
 {'key': 'textGlowColor', 'type': 'rgba', 'default': '#FFD966CC'},
 {'key': 'textGlowSize', 'type': 'number', 'default': 12, 'min': 1, 'max': 64, 'step': 1},
 {'key': 'textShadow', 'type': 'bool', 'default': False},
 {'key': 'textShadowColor', 'type': 'rgba', 'default': '#00000099'},
 {'key': 'textShadowOffsetX', 'type': 'number', 'default': 4, 'min': -32, 'max': 32, 'step': 1},
 {'key': 'textShadowOffsetY', 'type': 'number', 'default': 4, 'min': -32, 'max': 32, 'step': 1},
 {'key': 'textShadowBlur', 'type': 'number', 'default': 4, 'min': 0, 'max': 32, 'step': 0.5},
 {'key': 'subdivision', 'type': 'number', 'default': 0, 'min': 0, 'max': 3, 'step': 1},
 {'key': 'smooth', 'type': 'bool', 'default': False},
 {'key': 'cavity', 'type': 'bool', 'default': True},
 {'key': 'worldRidge', 'type': 'number', 'default': 2, 'min': 0, 'max': 2.5, 'step': 0.01},
 {'key': 'worldValley', 'type': 'number', 'default': 1.5, 'min': 0, 'max': 2.5, 'step': 0.01},
 {'key': 'screenRidge', 'type': 'number', 'default': 0.15, 'min': 0, 'max': 2, 'step': 0.01},
 {'key': 'screenValley', 'type': 'number', 'default': 0.15, 'min': 0, 'max': 2, 'step': 0.01},
 {'key': 'minAngle', 'type': 'number', 'default': 35, 'min': 0, 'max': 180, 'step': 1})
