import argparse
import json
import math
import bpy
import sys
import tempfile
import numpy as np
from pathlib import Path
from mathutils import Matrix, Quaternion, Vector

sys.path.insert(0, str(Path(__file__).resolve().parent))
import schema  # noqa: E402
from effects import EFFECT_KEYS, cavity_angle_mask, post_process_pixels  # noqa: E402
from render_cache import RenderCache  # noqa: E402


# ============================================================
# CONFIG
# ============================================================

# Effect sizes in the settings are authored for this resolution.
REFERENCE_RESOLUTION = 512

CAMERA_PADDING = 1.30

# Workbench uses studio lights, not scene lamp objects.
# Camera-space fill and rim directions; the key light comes from the settings.
FILL_LIGHT_DIRECTION = Vector((0.65, 0.10, 0.75)).normalized()
RIM_LIGHT_DIRECTION = Vector((0.00, -0.60, -0.80)).normalized()

AA_SAMPLES = ("OFF", "FXAA", "5", "8", "11", "16", "32")


# ============================================================
# CLI
# ============================================================

def get_args():
    if "--" not in sys.argv:
        raise RuntimeError(
            "\nUsage:\n"
            "blender --background --python renderer.py "
            "-- model/model2/model.obj render.png "
            "[--settings settings.json] [--size 512] [--aa 32] "
            "[--zoom 1.0] [--rotation X Y Z] "
            "[--orthogonal | --no-orthogonal]\n"
        )

    parser = argparse.ArgumentParser(
        description="Render an OBJ with Blender Workbench.",
        prog="blender --background --python renderer.py --",
    )
    parser.add_argument("input_path", type=Path, help="Input OBJ file")
    parser.add_argument("output_path", type=Path, help="Output PNG file")
    parser.add_argument("--settings", type=Path, help="JSON file of render settings (see schema.py)")
    parser.add_argument("--size", type=int, default=512, help="Square output size in pixels (default: 512)")
    parser.add_argument("--aa", choices=AA_SAMPLES, default="32", help="Anti-aliasing samples (default: 32)")
    parser.add_argument(
        "--orthogonal", action=argparse.BooleanOptionalAction, default=None,
        help="Use an orthographic camera; --no-orthogonal uses perspective",
    )
    parser.add_argument("--zoom", type=float, help="Positive camera zoom multiplier; larger values zoom in")
    parser.add_argument(
        "--rotation", type=float, nargs=3, metavar=("X", "Y", "Z"),
        help="Model pitch, yaw and roll in degrees about Roblox X, Y (up) and Z",
    )
    args = parser.parse_args(sys.argv[sys.argv.index("--") + 1:])

    settings = {}
    if args.settings is not None:
        settings = json.loads(args.settings.read_text())
    if args.orthogonal is not None:
        settings["orthographic"] = args.orthogonal
    if args.zoom is not None:
        if not math.isfinite(args.zoom) or args.zoom <= 0:
            parser.error("--zoom must be finite and greater than zero")
        settings["zoom"] = args.zoom
    if args.rotation is not None:
        if not all(math.isfinite(angle) for angle in args.rotation):
            parser.error("--rotation angles must be finite")
        settings["pitch"], settings["yaw"], settings["roll"] = args.rotation
    if args.size <= 0:
        parser.error("--size must be positive")

    input_path = args.input_path.resolve()
    if not input_path.exists():
        raise FileNotFoundError(input_path)
    if input_path.suffix.lower() != ".obj":
        raise RuntimeError(f"Expected .obj, got: {input_path}")

    return input_path, args.output_path.resolve(), schema.normalize(settings), args.size, args.aa


# ============================================================
# CLEAN SCENE
# ============================================================

def clear_scene():
    # An empty factory scene drops every datablock from previous models.
    bpy.ops.wm.read_factory_settings(use_empty=True)


# ============================================================
# IMPORT OBJ
# ============================================================

def import_obj(path):
    print(f"Importing OBJ: {path}")
    # Roblox exports Y-up OBJ files. Blender resolves mtllib and texture
    # paths relative to the OBJ/MTL files automatically.
    bpy.ops.wm.obj_import(
        filepath=str(path),
        forward_axis="NEGATIVE_Z",
        up_axis="Y",
    )
    with path.open(errors="replace") as source:
        return "Generated by Roblox Studio" in source.read(512)


# ============================================================
# MATERIAL HELPERS
# ============================================================

def find_principled(material):
    if not material.use_nodes:
        return None

    for node in material.node_tree.nodes:
        if node.type == "BSDF_PRINCIPLED":
            return node

    return None


def find_base_color_image_node(material, principled):
    """
    Find the image texture that ultimately supplies Principled Base Color.

    Normally glTF produces:

        Image Texture
             |
             v
        Principled BSDF Base Color

    Sometimes there may be intermediate nodes, so this does a small
    recursive traversal backwards through the graph.
    """

    if principled is None:
        return None

    base_color = principled.inputs.get("Base Color")

    if base_color is None:
        return None

    if not base_color.is_linked:
        return None

    visited = set()

    def search_socket(socket):
        for link in socket.links:
            node = link.from_node

            if node in visited:
                continue

            visited.add(node)

            if node.type == "TEX_IMAGE":
                if node.image is not None:
                    return node

            # Search backwards through inputs.
            for input_socket in node.inputs:
                if input_socket.is_linked:
                    result = search_socket(input_socket)

                    if result is not None:
                        return result

        return None

    return search_socket(base_color)


# ============================================================
# FIX UV MAPS
# ============================================================

def prepare_uv_maps(obj):
    mesh = obj.data

    if not hasattr(mesh, "uv_layers"):
        return False

    if len(mesh.uv_layers) == 0:
        print(
            f"WARNING: {obj.name} has no UV map."
        )
        return False

    # OBJ import creates the UV layer from vt coordinates.
    # Make absolutely sure one is active.
    uv = mesh.uv_layers.active

    if uv is None:
        uv = mesh.uv_layers[0]
        mesh.uv_layers.active = uv

    try:
        uv.active_render = True
    except Exception:
        pass

    print(
        f"  UV: {obj.name} -> {uv.name}"
    )

    return True


# ============================================================
# PREPARE MATERIALS FOR WORKBENCH
# ============================================================

def roblox_surface_atlas_neutral(image):
    """Recognize the legacy 128 x 2048 surface-detail atlas by its pixels."""
    if tuple(image.size) != (128, 2048):
        return None
    pixels = np.empty(128 * 2048 * 4, dtype=np.float32)
    image.pixels.foreach_get(pixels)
    pixels = pixels.reshape(2048, 128, 4)
    border = pixels[0, :, :3]
    # The atlas's smooth surface is neutral midgray, not a gray albedo.
    if not np.allclose(border, 128 / 255, atol=1 / 255):
        return None
    return tuple(border.mean(axis=0))


def prepare_surface_atlas_uvs(objects, material):
    """Repeat U and clamp V for the legacy Roblox surface atlas."""
    # Workbench repeats both axes regardless of the image node's extension.
    # Keep out-of-range V inside the smooth border, away from wrap filtering.
    margin = 0.5 / 2048
    for obj in objects:
        uv = obj.data.uv_layers.active
        if uv is None:
            continue
        for face in obj.data.polygons:
            if obj.data.materials[face.material_index] != material:
                continue
            for loop_index in face.loop_indices:
                coord = uv.data[loop_index].uv
                coord.y = min(max(coord.y, margin), 1.0 - margin)


def make_workbench_texture(image, rgba, cache, neutral=None, opaque=False):
    """Bake MTL Kd into the diffuse image, since Workbench ignores shaders."""
    key = (image.as_pointer(), tuple(rgba), neutral, opaque)
    if key in cache:
        return cache[key]

    width, height = image.size
    if not width or not height:
        raise RuntimeError(f"Could not load diffuse texture: {image.filepath}")

    pixels = np.empty(width * height * 4, dtype=np.float32)
    image.pixels.foreach_get(pixels)
    pixels = pixels.reshape(-1, 4)
    rgb = pixels[:, :3]
    if neutral is not None:
        # Convert the atlas's neutral gray to white before applying Kd.
        # Leave ordinary diffuse maps on the standard MTL path.
        rgb = np.clip(rgb / np.asarray(neutral), 0.0, 1.0)
    # Byte-backed sRGB images expose encoded pixel values. Multiply colors
    # in linear space, then encode for the generated sRGB texture.
    if image.colorspace_settings.name == "sRGB":
        rgb = np.where(rgb <= 0.04045, rgb / 12.92,
                       ((rgb + 0.055) / 1.055) ** 2.4)
    rgb = np.maximum(rgb * np.asarray(rgba[:3]), 0.0)
    pixels[:, :3] = np.where(rgb <= 0.0031308, rgb * 12.92,
                            1.055 * rgb ** (1.0 / 2.4) - 0.055)
    if opaque:
        pixels[:, 3] = 1.0
    else:
        pixels[:, 3] *= rgba[3]

    tinted = bpy.data.images.new(
        f"{image.name}_workbench_{len(cache)}",
        width=width, height=height, alpha=True,
    )
    tinted.colorspace_settings.name = "sRGB"
    tinted.pixels.foreach_set(pixels.ravel())
    tinted.update()
    cache[key] = tinted
    return tinted


def prepare_materials(objects, roblox_export=False):
    """Expose MTL diffuse colors and tinted diffuse maps to Workbench.

    Returns per-material state so transparency can be toggled per render.
    """
    print("\n========== MATERIAL SETUP ==========")
    processed_materials = set()
    texture_cache = {}
    states = []

    for obj in objects:
        prepare_uv_maps(obj)
        for material in obj.data.materials:
            if material is None or material in processed_materials:
                continue
            processed_materials.add(material)

            # OBJ import preserves MTL Kd/d here, even with a linked texture.
            # Reading the shader's default is unsafe for linked glTF graphs.
            rgba = tuple(material.diffuse_color)
            principled = find_principled(material)
            # The importer stores MTL d on the shader's Alpha input, not the viewport color.
            alpha_input = principled.inputs.get("Alpha") if principled is not None else None
            if alpha_input is not None and not alpha_input.is_linked:
                rgba = (*rgba[:3], float(alpha_input.default_value))
            print(f"Material: {material.name}, diffuse: {rgba}")
            state = {"material": material, "rgba": rgba, "node": None}
            states.append(state)
            image_node = find_base_color_image_node(material, principled)
            if not material.use_nodes:
                continue

            nodes = material.node_tree.nodes
            for node in nodes:
                node.select = False
            # Do not pick a normal, roughness, or emission map as base color.
            nodes.active = None
            if image_node is None:
                print("  No diffuse texture. Using material color.")
                continue

            image = image_node.image
            neutral = roblox_surface_atlas_neutral(image) if roblox_export else None
            if neutral is not None:
                prepare_surface_atlas_uvs(objects, material)
                print("  Roblox surface atlas: neutral detail, clamped V")
            # Roblox full-color maps already contain the surface colors.
            # Exported Kd can be the part's skin/base color; multiplying it
            # into clothing and other painted areas adds an unwanted tint.
            texture_rgba = (
                (1.0, 1.0, 1.0, rgba[3])
                if roblox_export and neutral is None else rgba
            )
            preview_node = nodes.new("ShaderNodeTexImage")
            preview_node.name = "Workbench Diffuse"
            preview_node.label = "Workbench diffuse texture"
            preview_node.select = True
            nodes.active = preview_node
            state.update(
                node=preview_node, image=image, texture_rgba=texture_rgba,
                neutral=neutral, cache=texture_cache,
            )
            print(f"  Workbench texture: {image.name}")

    print(f"Materials: {len(states)}\n")
    return states


def apply_material_settings(states, settings):
    transparent = settings["transparency"]
    for state in states:
        material = state["material"]
        material.roughness = settings["roughness"]
        material.metallic = 0.0
        alpha = state["rgba"][3] if transparent else 1.0
        material.diffuse_color = (*state["rgba"][:3], alpha)
        material.surface_render_method = "BLENDED" if transparent else "DITHERED"
        if state["node"] is not None:
            state["node"].image = make_workbench_texture(
                state["image"], state["texture_rgba"], state["cache"],
                state["neutral"], opaque=not transparent,
            )


# ============================================================
# GEOMETRY
# ============================================================

def make_smooth_mesh(mesh):
    """Copy a mesh with merged split vertices, smooth shading and no custom normals."""
    import bmesh

    smooth = mesh.copy()
    smooth.name = f"{mesh.name}_smooth"
    bm = bmesh.new()
    try:
        bm.from_mesh(smooth)
        bmesh.ops.remove_doubles(bm, verts=bm.verts, dist=1e-5)
        bm.to_mesh(smooth)
    finally:
        bm.free()
    for name in ("custom_normal",):
        attribute = smooth.attributes.get(name)
        if attribute is not None:
            smooth.attributes.remove(attribute)
    if smooth.has_custom_normals:
        smooth.normals_split_custom_set([(0.0, 0.0, 0.0)] * len(smooth.loops))
    smooth.shade_smooth()
    return smooth


def apply_geometry_settings(model, settings):
    levels = int(settings["subdivision"])
    for obj, original in zip(model["objects"], model["meshes"]):
        if settings["smooth"]:
            smooth = model["smooth_meshes"].get(original.name)
            if smooth is None:
                smooth = make_smooth_mesh(original)
                model["smooth_meshes"][original.name] = smooth
            obj.data = smooth
        else:
            obj.data = original

        modifier = obj.modifiers.get("Prism Subdivision")
        if levels == 0:
            if modifier is not None:
                obj.modifiers.remove(modifier)
            continue
        if modifier is None:
            modifier = obj.modifiers.new("Prism Subdivision", "SUBSURF")
        modifier.levels = levels
        modifier.render_levels = levels
    bpy.context.view_layer.update()


# ============================================================
# BOUNDS
# ============================================================

def calculate_bounds(objects):
    points = []

    depsgraph = bpy.context.evaluated_depsgraph_get()

    for original_obj in objects:
        obj = original_obj.evaluated_get(depsgraph)

        for corner in obj.bound_box:
            world_corner = (
                obj.matrix_world
                @ Vector(corner)
            )

            points.append(world_corner)

    if not points:
        raise RuntimeError(
            "Could not calculate model bounds."
        )

    minimum = Vector((
        min(p.x for p in points),
        min(p.y for p in points),
        min(p.z for p in points),
    ))

    maximum = Vector((
        max(p.x for p in points),
        max(p.y for p in points),
        max(p.z for p in points),
    ))

    center = (
        minimum + maximum
    ) * 0.5

    size = maximum - minimum

    return center, size


def parent_depth(obj):
    depth = 0
    parent = obj.parent
    while parent is not None:
        depth += 1
        parent = parent.parent
    return depth


def stance_matrix(pitch, yaw, roll):
    """Roblox-style orientation (CFrame.fromOrientation: Y, then X, then Z) in Blender axes.

    Roblox X is Blender X, Roblox Y (up) is Blender Z and Roblox Z is Blender -Y.
    """
    return (
        Matrix.Rotation(math.radians(yaw), 4, "Z")
        @ Matrix.Rotation(math.radians(pitch), 4, "X")
        @ Matrix.Rotation(math.radians(-roll), 4, "Y")
    )


def rotate_model(model, angles):
    """Rotate the assembled model about its bounds center in world space.

    Always starts from the imported transforms so repeated renders don't accumulate.
    """
    # Restore parents before children so child world matrices stay correct.
    for obj, matrix in sorted(model["matrices"], key=lambda item: parent_depth(item[0])):
        obj.matrix_world = matrix
    bpy.context.view_layer.update()
    if not any(angles):
        return
    center, _ = calculate_bounds(model["objects"])
    transform = (
        Matrix.Translation(center)
        @ stance_matrix(*angles)
        @ Matrix.Translation(-center)
    )
    matrices = [(obj, transform @ obj.matrix_world) for obj in model["objects"]]

    # Snapshot world transforms first, then assign parents before children.
    for obj, matrix in sorted(matrices, key=lambda item: parent_depth(item[0])):
        obj.matrix_world = matrix
    bpy.context.view_layer.update()


# ============================================================
# CAMERA
# ============================================================

def spherical_direction(rotation, elevation):
    """Blender world direction toward the camera.

    Rotation 0 faces the model's Roblox front (-Z, which imports as Blender +Y);
    positive rotation orbits toward Roblox +X, positive elevation looks from above.
    """
    rotation, elevation = math.radians(rotation), math.radians(elevation)
    return Vector((
        math.sin(rotation) * math.cos(elevation),
        math.cos(rotation) * math.cos(elevation),
        math.sin(elevation),
    ))


def view_direction(rotation, elevation):
    """Camera-space direction: x right, y up, z toward the viewer."""
    rotation, elevation = math.radians(rotation), math.radians(elevation)
    return Vector((
        math.sin(rotation) * math.cos(elevation),
        math.sin(elevation),
        math.cos(rotation) * math.cos(elevation),
    )).normalized()


def get_camera():
    scene = bpy.context.scene
    camera = scene.objects.get("PreviewCamera")
    if camera is None:
        camera_data = bpy.data.cameras.new("PreviewCamera")
        camera = bpy.data.objects.new("PreviewCamera", camera_data)
        scene.collection.objects.link(camera)
    scene.camera = camera
    return camera


def configure_camera(center, size, settings):
    camera = get_camera()
    camera_data = camera.data
    orthogonal = settings["orthographic"]

    camera_data.type = "ORTHO" if orthogonal else "PERSP"
    camera_data.sensor_fit = "HORIZONTAL"

    diameter = max(
        size.x,
        size.y,
        size.z,
        0.01,
    )

    camera_data.ortho_scale = (
        diameter * CAMERA_PADDING / settings["zoom"]
    )

    distance = diameter * 5.0
    if not orthogonal:
        if settings["fovAuto"]:
            # Match the orthographic framing at the model's center plane.
            camera_data.lens = (
                camera_data.sensor_width * distance / camera_data.ortho_scale
            )
        else:
            camera_data.angle = math.radians(settings["fov"])
            distance = (camera_data.ortho_scale / 2) / math.tan(camera_data.angle / 2)

    direction = spherical_direction(settings["cameraRotation"], settings["cameraElevation"])
    camera.location = center + direction * distance
    look = (-direction).to_track_quat("-Z", "Y")
    roll = Quaternion((0.0, 0.0, 1.0), math.radians(settings["cameraRoll"]))
    camera.rotation_mode = "QUATERNION"
    camera.rotation_quaternion = look @ roll

    camera_data.clip_start = max(
        min(diameter * 0.001, distance * 0.01),
        0.0001,
    )

    camera_data.clip_end = max(
        distance + diameter * 30.0,
        1000.0,
    )
    bpy.context.view_layer.update()
    return camera


# ============================================================
# WORKBENCH
# ============================================================

class StudioLights:
    """Register Workbench studio rigs without saving preferences, cached by settings."""

    def __init__(self):
        self.directory = tempfile.TemporaryDirectory(prefix="renderer-studio-")
        self.key = None
        self.name = None

    def get(self, settings):
        sun = self.light_color(settings["sunColor"], settings["sunIntensity"])
        secondary = self.light_color(settings["secondaryColor"], settings["secondaryIntensity"])
        ambient = self.light_color(settings["ambientColor"], settings["ambientIntensity"])
        key_direction = view_direction(settings["sunRotation"], settings["sunElevation"])
        specular = settings["specular"]
        # Camera-space direction, diffuse RGB, softness, specular RGB.
        lights = (
            (tuple(key_direction), sun, 1.0, tuple(c * specular for c in sun)),
            (tuple(FILL_LIGHT_DIRECTION), secondary, 1.0, tuple(c * specular for c in secondary)),
            (tuple(RIM_LIGHT_DIRECTION), secondary, 1.0, tuple(c * specular for c in secondary)),
        )
        key = (lights, ambient)
        preferences = bpy.context.preferences
        if key == self.key and self.name in preferences.studio_lights:
            return self.name
        previous = preferences.studio_lights.get(self.name) if self.name else None
        self.name = self.create(lights, ambient)
        self.key = key
        if previous is not None:
            preferences.studio_lights.remove(previous)
        return self.name

    @staticmethod
    def light_color(hex_color, intensity):
        # Studio light RGB values are linear light, not display-space colors.
        return tuple(schema.srgb_to_linear(c) * intensity for c in schema.hex_to_rgb(hex_color))

    def create(self, lights, ambient):
        preferences = bpy.context.preferences
        system = preferences.system
        light_properties = (
            "use", "direction", "diffuse_color", "specular_color", "smooth",
        )
        original_ambient = tuple(system.light_ambient)
        original_lights = [
            {
                name: tuple(getattr(light, name))
                if name.endswith("color") or name == "direction"
                else getattr(light, name)
                for name in light_properties
            }
            for light in system.solid_lights
        ]

        try:
            system.light_ambient = ambient
            for index, light in enumerate(system.solid_lights):
                light.use = index < len(lights)
                if light.use:
                    direction, diffuse, softness, specular = lights[index]
                    light.direction = direction
                    light.diffuse_color = diffuse
                    light.specular_color = specular
                    light.smooth = softness

            # Keep the preset until exit: Blender can load it lazily when
            # rendering, after the original preferences have been restored.
            # A unique name avoids reusing cached lighting on subsequent renders.
            with tempfile.NamedTemporaryFile(
                dir=self.directory.name, suffix=".sl", delete=False,
            ) as preset:
                studio_path = preset.name
            studio = preferences.studio_lights.new(studio_path)
        finally:
            system.light_ambient = original_ambient
            for light, values in zip(system.solid_lights, original_lights):
                for name, value in values.items():
                    setattr(light, name, value)

        # Reload the saved rig after restoring the editable default lights.
        preferences.studio_lights.remove(studio)
        studio = preferences.studio_lights.load(studio_path, "STUDIO")
        return studio.name


def configure_workbench(settings, studio_lights, size, aa):
    scene = bpy.context.scene

    scene.render.engine = "BLENDER_WORKBENCH"

    shading = scene.display.shading

    # ========================================================
    # THIS IS THE IMPORTANT PART
    # ========================================================

    shading.light = "STUDIO"
    shading.studio_light = studio_lights.get(settings)

    # Workbench will now use:
    #
    #   active Image Texture node
    #          +
    #   active UV map
    #
    # If no texture exists it automatically falls back to
    # the material's Viewport Display color.
    shading.color_type = "TEXTURE"

    # ========================================================
    # CAVITY
    # ========================================================

    shading.show_cavity = settings["cavity"] and any(settings[name] > 0 for name in (
        "worldRidge", "worldValley", "screenRidge", "screenValley",
    ))
    shading.cavity_type = "BOTH"

    shading.curvature_ridge_factor = settings["screenRidge"]
    shading.curvature_valley_factor = settings["screenValley"]
    # BOTH combines curvature with screen-space ambient occlusion.
    # Set both effects explicitly instead of inheriting Blender defaults.
    shading.cavity_ridge_factor = settings["worldRidge"]
    shading.cavity_valley_factor = settings["worldValley"]

    # ========================================================
    # LIGHTING
    # ========================================================

    # Keep the daylight direction consistent in the thumbnail's camera view.
    shading.use_studiolight_view_rotation = False
    shading.studiolight_rotate_z = 0.0

    shading.show_specular_highlight = settings["specular"] > 0

    # ========================================================
    # SHADOWS
    # ========================================================

    shading.show_shadows = settings["castShadows"]

    shading.shadow_intensity = settings["shadowIntensity"]
    # Workbench's shadow direction is separate from its studio diffuse rig.
    # Transform the same key direction to world space for matching shadows.
    key_direction = view_direction(settings["sunRotation"], settings["sunElevation"])
    scene.display.light_direction = (
        scene.camera.matrix_world.to_quaternion() @ key_direction
    )
    scene.display.render_aa = aa

    # ========================================================
    # BACKGROUND
    # ========================================================

    scene.render.film_transparent = True

    # ========================================================
    # OUTPUT
    # ========================================================

    scene.render.resolution_x = size
    scene.render.resolution_y = size
    scene.render.resolution_percentage = 100

    scene.render.image_settings.file_format = "PNG"
    scene.render.image_settings.color_mode = "RGBA"
    scene.render.image_settings.color_depth = "8"

    # ========================================================
    # COLOR MANAGEMENT
    # ========================================================

    # Standard preserves the reference's texture colors and dark metal tones.
    scene.view_settings.view_transform = "Standard"
    scene.view_settings.look = "None"
    scene.view_settings.exposure = settings["exposure"]
    scene.view_settings.gamma = 1.0
    scene.display_settings.display_device = "sRGB"
    scene.view_settings.use_curve_mapping = False
    if hasattr(scene.view_settings, "use_white_balance"):
        scene.view_settings.use_white_balance = False


# ============================================================
# DEBUG
# ============================================================

def print_scene_info(objects):
    print("")
    print("========== SCENE ==========")

    print(
        f"Blender: {bpy.app.version_string}"
    )

    print(
        f"Mesh objects: {len(objects)}"
    )

    for obj in objects:
        print("")
        print(f"Object: {obj.name}")
        print(
            f"  Vertices: {len(obj.data.vertices)}"
        )
        print(
            f"  Faces: {len(obj.data.polygons)}"
        )
        print(
            f"  UV maps: {len(obj.data.uv_layers)}"
        )
        print(
            f"  Materials: {len(obj.data.materials)}"
        )

    print("")
    print("===========================")
    print("")


# ============================================================
# POST PROCESSING
# ============================================================

def load_png_pixels(path):
    """Read straight-alpha display-space pixels without retaining an image."""
    image = bpy.data.images.load(str(path), check_existing=False)
    try:
        image.alpha_mode = "STRAIGHT"
        width, height = image.size
        pixels = np.empty(width * height * 4, dtype=np.float32)
        image.pixels.foreach_get(pixels)
        return pixels.reshape(height, width, 4)
    finally:
        bpy.data.images.remove(image)


def save_png_pixels(pixels, path):
    """Write straight-alpha display-space pixels (bottom row first) to a PNG."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    height, width = pixels.shape[:2]
    image = bpy.data.images.new("Prism Output", width=width, height=height, alpha=True)
    try:
        image.alpha_mode = "STRAIGHT"
        image.pixels.foreach_set(np.ascontiguousarray(pixels, dtype=np.float32).ravel())
        image.filepath_raw = str(path)
        image.file_format = "PNG"
        image.save()
    finally:
        bpy.data.images.remove(image)


def render_surface_normals(path, objects):
    """Render camera-space corner normals as flat RGB, restoring scene state."""
    scene = bpy.context.scene
    shading = scene.display.shading
    settings = {name: getattr(shading, name) for name in (
        "light", "color_type", "show_cavity", "show_shadows",
        "show_specular_highlight",
    )}
    view_transform = scene.view_settings.view_transform
    exposure = scene.view_settings.exposure
    color_depth = scene.render.image_settings.color_depth
    filepath = scene.render.filepath
    film_transparent = scene.render.film_transparent
    originals = []
    bpy.context.view_layer.update()
    camera_rotation = scene.camera.matrix_world.to_3x3().inverted()
    depsgraph = bpy.context.evaluated_depsgraph_get()
    try:
        # Copies retain UVs/materials and respect modifiers without changing
        # the original mesh's normals, materials, or active color attributes.
        for obj in objects:
            if obj.hide_render:
                continue
            mesh = bpy.data.meshes.new_from_object(
                obj.evaluated_get(depsgraph), depsgraph=depsgraph,
            )
            modifiers = [(modifier, modifier.show_render) for modifier in obj.modifiers]
            originals.append((obj, obj.data, mesh, modifiers))
            normals = np.empty(len(mesh.loops) * 3, dtype=np.float32)
            mesh.corner_normals.foreach_get("vector", normals)
            normals = normals.reshape(-1, 3)
            transform = camera_rotation @ obj.matrix_world.to_3x3().inverted().transposed()
            normals = normals @ np.asarray(transform, dtype=np.float32).T
            lengths = np.linalg.norm(normals, axis=1, keepdims=True)
            np.divide(normals, lengths, out=normals, where=lengths > 1e-6)
            colors = np.ones((len(mesh.loops), 4), dtype=np.float32)
            encoded = normals * 0.5 + 0.5
            # Workbench converts vertex RGB from sRGB to linear even for
            # float attributes. Compensate so Raw output stores the normals.
            colors[:, :3] = np.where(
                encoded <= 0.0031308, encoded * 12.92,
                1.055 * np.maximum(encoded, 0.0) ** (1 / 2.4) - 0.055,
            )
            attribute = mesh.color_attributes.new(
                name="Cavity Surface Normals", type="FLOAT_COLOR", domain="CORNER",
            )
            attribute.data.foreach_set("color", colors.ravel())
            mesh.color_attributes.active_color = attribute
            mesh.color_attributes.render_color_index = mesh.color_attributes.find(attribute.name)
            obj.data = mesh
            for modifier, _ in modifiers:
                modifier.show_render = False
        shading.light = "FLAT"
        shading.color_type = "VERTEX"
        shading.show_cavity = False
        shading.show_shadows = False
        shading.show_specular_highlight = False
        scene.view_settings.view_transform = "Raw"
        scene.view_settings.exposure = 0.0
        scene.render.image_settings.color_depth = "16"
        scene.render.film_transparent = True
        scene.render.filepath = str(path)
        bpy.ops.render.render(write_still=True)
    finally:
        for obj, original, mesh, modifiers in originals:
            obj.data = original
            for modifier, show_render in modifiers:
                modifier.show_render = show_render
            bpy.data.meshes.remove(mesh)
        for name, value in settings.items():
            setattr(shading, name, value)
        scene.view_settings.view_transform = view_transform
        scene.view_settings.exposure = exposure
        scene.render.image_settings.color_depth = color_depth
        scene.render.filepath = filepath
        scene.render.film_transparent = film_transparent


# ============================================================
# RENDER
# ============================================================

def render_pixels(directory, objects, minimum_angle, cache=None, key=None, normal_key=None):
    """Render the configured scene and return display-space RGBA, bottom row first."""
    scene = bpy.context.scene
    shading = scene.display.shading
    directory = Path(directory)
    show_cavity = shading.show_cavity
    compression = scene.render.image_settings.compression

    def capture(name, cache_key, normals=False, cavity=False):
        pixels = cache.get(cache_key) if cache is not None else None
        if pixels is None:
            path = directory / f"{name}.png"
            if normals:
                render_surface_normals(path, objects)
            else:
                shading.show_cavity = cavity
                scene.render.filepath = str(path)
                bpy.ops.render.render(write_still=True)
            pixels = load_png_pixels(path)
            if cache is not None:
                cache.put(cache_key, pixels)
        return pixels

    try:
        # These files are transient. Compression spends CPU to save disk space
        # only to immediately decode the same pixels again.
        scene.render.image_settings.compression = 0
        if not show_cavity or minimum_angle >= 180:
            return capture("base", ("base", normal_key))
        full = capture("cavity", ("cavity", key), cavity=True)
        if minimum_angle <= 0:
            return full
        base = capture("base", ("base", normal_key))
        normals = capture("normals", ("normals", normal_key), normals=True)
        mask = cavity_angle_mask(normals, minimum_angle)
        pixels = full.copy()
        pixels[..., :3] = base[..., :3] + mask[..., None] * (full[..., :3] - base[..., :3])
        return pixels
    finally:
        shading.show_cavity = show_cavity
        scene.render.image_settings.compression = compression


class Renderer:
    """Keeps imported models loaded so settings changes only re-render.

    Each model lives in its own collection; only the one being rendered is visible.
    """

    MAX_MODELS = 12

    def __init__(self):
        clear_scene()
        self.models = {}
        self.studio_lights = StudioLights()
        self.directory = tempfile.TemporaryDirectory(prefix="renderer-")
        self.passes = RenderCache(max_bytes=64 * 1024 * 1024)
        self.base_renders = RenderCache(max_bytes=32 * 1024 * 1024)
        self.effect_masks = RenderCache(max_bytes=16 * 1024 * 1024)

    def load(self, input_path):
        """Import an OBJ once; returns its key for render()."""
        key = str(Path(input_path).resolve())
        model = self.models.pop(key, None)
        if model is None:
            model = self.import_model(Path(key))
        # Dicts keep insertion order, so re-inserting marks the model as most recent.
        self.models[key] = model
        while len(self.models) > self.MAX_MODELS:
            self.unload(next(iter(self.models)))
        return key

    def import_model(self, path):
        scene = bpy.context.scene
        collection = bpy.data.collections.new(f"Model {path.parent.name}")
        scene.collection.children.link(collection)
        view_layer = bpy.context.view_layer
        view_layer.active_layer_collection = view_layer.layer_collection.children[collection.name]
        try:
            roblox_export = import_obj(path)
        finally:
            view_layer.active_layer_collection = view_layer.layer_collection

        objects = [obj for obj in collection.all_objects if obj.type == "MESH"]
        if not objects:
            self.remove_collection(collection)
            raise RuntimeError("OBJ imported but contains no mesh objects.")

        print_scene_info(objects)
        return {
            "collection": collection,
            "objects": objects,
            "meshes": [obj.data for obj in objects],
            "smooth_meshes": {},
            "matrices": [(obj, obj.matrix_world.copy()) for obj in objects],
            "materials": prepare_materials(objects, roblox_export),
        }

    def unload(self, key):
        model = self.models.pop(key, None)
        if model is not None:
            self.remove_collection(model["collection"])

    @staticmethod
    def remove_collection(collection):
        for obj in list(collection.all_objects):
            bpy.data.objects.remove(obj, do_unlink=True)
        bpy.data.collections.remove(collection)
        bpy.data.orphans_purge(do_local_ids=True, do_linked_ids=True, do_recursive=True)

    def render(self, key, settings, size=512, aa="32"):
        """Render a loaded model; returns straight-alpha display RGBA, bottom row first."""
        model = self.models.get(key)
        if model is None:
            raise RuntimeError("Model is not loaded.")
        settings = schema.normalize(settings)
        geometry_settings = {name: value for name, value in settings.items() if name not in EFFECT_KEYS}
        cache_key = (key, json.dumps(geometry_settings, sort_keys=True), size, aa)
        pixels = self.base_renders.get(cache_key)
        if pixels is not None:
            return post_process_pixels(pixels, settings, size, self.effect_masks, cache_key)
        for other in self.models.values():
            other["collection"].hide_render = other is not model

        apply_material_settings(model["materials"], settings)
        apply_geometry_settings(model, settings)
        rotate_model(model, (settings["pitch"], settings["yaw"], settings["roll"]))
        center, bounds = calculate_bounds(model["objects"])
        configure_camera(center, bounds, settings)
        configure_workbench(settings, self.studio_lights, size, aa)

        cavity_keys = {"cavity", "minAngle", "worldRidge", "worldValley", "screenRidge", "screenValley"}
        base_settings = {name: value for name, value in geometry_settings.items() if name not in cavity_keys}
        base_key = (key, json.dumps(base_settings, sort_keys=True), size, aa)
        full_settings = {name: value for name, value in geometry_settings.items() if name != "minAngle"}
        full_key = (key, json.dumps(full_settings, sort_keys=True), size, aa)
        pixels = render_pixels(self.directory.name, model["objects"], settings["minAngle"], self.passes, full_key, base_key)
        self.base_renders.put(cache_key, pixels)
        return post_process_pixels(pixels, settings, size, self.effect_masks, cache_key)


def to_rgba8_top_down(pixels):
    """Convert renderer output to top-down RGBA8 bytes, as EditableImage expects."""
    return (np.clip(pixels[::-1], 0.0, 1.0) * 255 + 0.5).astype(np.uint8).tobytes()


# ============================================================
# MAIN
# ============================================================

def main():
    input_path, output_path, settings, size, aa = get_args()

    print("")
    print("==========================================")
    print("         OBJ WORKBENCH RENDERER")
    print("==========================================")
    print("")
    print("Input:")
    print(input_path)
    print("")
    print("Output:")
    print(output_path)
    print("")

    renderer = Renderer()
    key = renderer.load(input_path)
    pixels = renderer.render(key, settings, size, aa)
    save_png_pixels(pixels, output_path)

    print("")
    print("==========================================")
    print("SUCCESS")
    print(output_path)
    print("==========================================")
    print("")


if __name__ == "__main__":
    main()
