-- ISC License
--
-- Copyright (c) 2026 Lucide Icons and Contributors
--
-- Permission to use, copy, modify, and/or distribute this software for any
-- purpose with or without fee is hereby granted, provided that the above
-- copyright notice and this permission notice appear in all copies.
--
-- THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
-- WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
-- MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
-- ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
-- WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
-- ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
-- OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

-- Lucide icons, uploaded with raven under user:5048508312.
-- Use the image IDs inside the uploaded Decals, not the Decal IDs themselves.
-- Source SVGs, PNGs and license are in assets/lucide and third_party/lucide-LICENSE.
return table.freeze({
	camera = "rbxassetid://92987198797474", -- camera, Decal 100068494706427
	select = "rbxassetid://118288486247565", -- mouse-pointer-2, Decal 114073134665938
	templates = "rbxassetid://70816354554356", -- file-braces, Decal 115952813879541
	settings = "rbxassetid://97883459364638", -- cog, Decal 118786212222120
	history = "rbxassetid://94615980529378", -- book, Decal 101447467057570
})
